export default {
    // Cats
    TOGGLE_IMAGE_LOADING: 'cats.TOGGLE_IMAGE_LOADING',
    LOAD_CAT_IMAGE: 'cats.LOAD_CAT_IMAGE',

    // Theme
    SET_ACTIVE_ID: 'theme.SET_ACTIVE_ID',
    SET_BACKGROUND_COLOR: 'theme.SET_BACKGROUND_COLOR',

    LOAD_YOUTUBE_INFO: 'LOAD_YOUTUBE_INFO',
    LOAD_YOUTUBE_INFO_SUCESS: 'LOAD_YOUTUBE_INFO_SUCESS',
    LOAD_YOUTUBE_INFO_FAIL: 'LOAD_YOUTUBE_INFO_FAIL',
    SET_LOADING_INDICATOR: 'SET_LOADING_INDICATOR'
}
