export default {
    // Cats
    TOGGLE_IMAGE_LOADING: 'cats.TOGGLE_IMAGE_LOADING',
    REMOVE_CAT_IMAGE: 'cats.REMOVE_CAT_IMAGE',
    LOAD_CAT_IMAGE: 'cats.LOAD_CAT_IMAGE',
    LOAD_CAT_IMAGE_SUCCESS: 'cats.LOAD_CAT_IMAGE_SUCCESS',
    LOAD_CAT_IMAGE_ERROR: 'cats.LOAD_CAT_IMAGE_ERROR',

    // Theme
    REGISTER_ELEMENT: 'theme.REGISTER_ELEMENT',
    SET_ACTIVE_ID: 'theme.SET_ACTIVE_ID',
    SET_BACKGROUND_COLOR: 'theme.SET_BACKGROUND_COLOR'
}
